name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true  # Enables caching of Deno dependencies

      - name: Install backend dependencies
        run: |
          deno cache main.ts

      - name: Install frontend deps
        run: |
          npm install

      - name: Build frontend
        run: |
          npm run build

      - name: Deploy to Deno Deploy
        run: |
          curl -fsSL https://deno.land/x/deploy/install.sh | sh
          export DENO_DEPLOY_TOKEN="${{ secrets.DENO_DEPLOY_TOKEN }}"
          deployctl deploy --project=yitsuken --token=$DENO_DEPLOY_TOKEN
